// apps/web/src/components/theme-toggle.tsx
import { useEffect, useState } from 'react';
import { Moon, Sun } from 'lucide-react';
import { Button } from '@/components/ui/button';

export function ThemeToggle() {
  const [dark, setDark] = useState(false);

  useEffect(() => {
    setDark(document.documentElement.classList.contains('dark'));
  }, []);

  const toggle = () => {
    const next = !dark;
    setDark(next);
    document.documentElement.classList.toggle('dark', next);
    try {
      localStorage.setItem('blog-theme', next ? 'dark' : 'light');
    } catch {
      /* ignore */
    }
  };

  return (
    <Button
      variant="outline"
      size="icon"
      className="rounded-full"
      onClick={toggle}
      aria-label="切换深浅色主题"
      title="切换深浅色主题"
    >
      {dark ? <Moon /> : <Sun />}
    </Button>
  );
}

// apps/admin/src/components/ThemeToggle.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';

const label = ref('夜');

function paint() {
  label.value =
    document.documentElement.getAttribute('data-theme') === 'dark' ? '日' : '夜';
}

function toggle() {
  const root = document.documentElement;
  const next = root.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
  root.setAttribute('data-theme', next);
  try {
    localStorage.setItem('blog-theme', next);
  } catch {
    /* ignore */
  }
  paint();
}

onMounted(paint);
</script>

<template>
  <button
    class="icon-btn"
    type="button"
    aria-label="切换深浅色"
    @click="toggle"
  >
    {{ label }}
  </button>
</template>
